import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { parseArgs } from 'node:util';
import type { SqlEntry } from '../index';
import { loadSqlCatalogSync, SqlLoaderError } from '../index';

const pkg = createRequire(import.meta.url)('../../package.json') as { version: string };

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const USAGE = 'Usage: sql-loader generate <dir> --out <file> [--format ts|js]';

interface TreeNode extends Map<string, TreeNode | string> {}

function buildNestedMap(entries: readonly SqlEntry[]): TreeNode {
  const root: TreeNode = new Map();
  for (const entry of entries) {
    const segments = entry.id.split('/');
    let node = root;
    for (let i = 0; i < segments.length - 1; i++) {
      const key = segments[i] ?? '';
      let next = node.get(key);
      if (next === undefined || typeof next === 'string') {
        next = new Map();
        node.set(key, next);
      }
      node = next;
    }
    node.set(segments[segments.length - 1] ?? '', entry.text);
  }
  return root;
}

// `__proto__` must be emitted as a computed key: in an object literal even a
// quoted "__proto__" key triggers prototype-setter semantics.
function emitKey(key: string): string {
  if (key === '__proto__') return '["__proto__"]';
  return IDENTIFIER_RE.test(key) ? key : JSON.stringify(key);
}

function emitValueNode(node: TreeNode, indent: string): string {
  const lines: string[] = ['{'];
  for (const [key, value] of node) {
    const rendered =
      typeof value === 'string' ? JSON.stringify(value) : emitValueNode(value, `${indent}  `);
    lines.push(`${indent}  ${emitKey(key)}: ${rendered},`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function emitTypeNode(node: TreeNode, indent: string): string {
  const lines: string[] = ['{'];
  for (const [key, value] of node) {
    const keyText = key === '__proto__' || !IDENTIFIER_RE.test(key) ? JSON.stringify(key) : key;
    const rendered = typeof value === 'string' ? 'string' : emitTypeNode(value, `${indent}  `);
    lines.push(`${indent}  readonly ${keyText}: ${rendered};`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function headerLines(hash: string, fileCount: number): string[] {
  return [
    `// @generated by sql-loader v${pkg.version} — do not edit`,
    `// sql-loader:generated v=1 hash=${hash} files=${fileCount}`,
  ];
}

function relativePosixPath(rootDir: string, filePath: string): string {
  return path.relative(rootDir, filePath).replaceAll('\\', '/');
}

function emitEntries(entries: readonly SqlEntry[], rootDir: string): string {
  const lines: string[] = ['['];
  for (const entry of entries) {
    const rel = relativePosixPath(rootDir, entry.filePath);
    lines.push(
      `  { id: ${JSON.stringify(entry.id)}, text: ${JSON.stringify(entry.text)}, ` +
        `hash: ${JSON.stringify(entry.hash)}, path: ${JSON.stringify(rel)} },`,
    );
  }
  lines.push(']');
  return lines.join('\n');
}

function queryIdUnion(entries: readonly SqlEntry[]): string {
  if (entries.length === 0) return 'never';
  return entries.map((entry) => JSON.stringify(entry.id)).join(' | ');
}

function emitTsModule(entries: readonly SqlEntry[], rootDir: string, hash: string): string {
  const tree = buildNestedMap(entries);
  return [
    ...headerLines(hash, entries.length),
    '',
    `export const queries = ${emitValueNode(tree, '')} as const;`,
    '',
    `export type SqlQueryId = ${queryIdUnion(entries)};`,
    '',
    'export interface SqlGeneratedEntry {',
    '  readonly id: SqlQueryId;',
    '  readonly text: string;',
    '  readonly hash: string;',
    '  readonly path: string;',
    '}',
    '',
    `export const entries: readonly SqlGeneratedEntry[] = ${emitEntries(entries, rootDir)};`,
    '',
    `export const sqlHash = ${JSON.stringify(hash)};`,
    '',
    'const byId = new Map<string, string>(entries.map((entry) => [entry.id, entry.text] as const));',
    '',
    'export function getSql(id: SqlQueryId): string {',
    '  const text = byId.get(id);',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emitted source code, not a mistaken template
    '  if (text === undefined) throw new Error(`Unknown SQL query ID: ${String(id)}`);',
    '  return text;',
    '}',
    '',
  ].join('\n');
}

function emitJsModule(entries: readonly SqlEntry[], rootDir: string, hash: string): string {
  const tree = buildNestedMap(entries);
  return [
    ...headerLines(hash, entries.length),
    '',
    `export const queries = ${emitValueNode(tree, '')};`,
    '',
    `export const entries = ${emitEntries(entries, rootDir)};`,
    '',
    `export const sqlHash = ${JSON.stringify(hash)};`,
    '',
    'const byId = new Map(entries.map((entry) => [entry.id, entry.text]));',
    '',
    'export function getSql(id) {',
    '  const text = byId.get(id);',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emitted source code, not a mistaken template
    '  if (text === undefined) throw new Error(`Unknown SQL query ID: ${String(id)}`);',
    '  return text;',
    '}',
    '',
  ].join('\n');
}

function emitDts(entries: readonly SqlEntry[], hash: string): string {
  const tree = buildNestedMap(entries);
  return [
    ...headerLines(hash, entries.length),
    '',
    `export type SqlQueryId = ${queryIdUnion(entries)};`,
    '',
    'export interface SqlGeneratedEntry {',
    '  readonly id: SqlQueryId;',
    '  readonly text: string;',
    '  readonly hash: string;',
    '  readonly path: string;',
    '}',
    '',
    `export declare const queries: ${emitTypeNode(tree, '')};`,
    '',
    'export declare const entries: readonly SqlGeneratedEntry[];',
    '',
    'export declare const sqlHash: string;',
    '',
    'export declare function getSql(id: SqlQueryId): string;',
    '',
  ].join('\n');
}

export function runGenerate(argv: string[]): number {
  let dir: string;
  let out: string;
  let format: string;
  try {
    const parsed = parseArgs({
      args: argv,
      options: {
        out: { type: 'string', short: 'o' },
        format: { type: 'string', default: 'ts' },
      },
      allowPositionals: true,
      strict: true,
    });
    const positional = parsed.positionals[0];
    if (positional === undefined || parsed.positionals.length !== 1) {
      throw new Error('expected exactly one <dir> argument');
    }
    if (parsed.values.out === undefined) throw new Error('--out <file> is required');
    dir = positional;
    out = parsed.values.out;
    format = parsed.values.format ?? 'ts';
    if (format !== 'ts' && format !== 'js') throw new Error('--format must be "ts" or "js"');
    if (format === 'ts' && !/\.(ts|mts)$/.test(out)) {
      throw new Error('--format ts requires an --out file ending in .ts or .mts');
    }
    if (format === 'js' && !/\.(js|mjs)$/.test(out)) {
      throw new Error('--format js requires an --out file ending in .js or .mjs');
    }
  } catch (error) {
    console.error(`sql-loader generate: ${error instanceof Error ? error.message : error}`);
    console.error(USAGE);
    return 2;
  }

  let catalog: ReturnType<typeof loadSqlCatalogSync>;
  try {
    catalog = loadSqlCatalogSync(dir);
  } catch (error) {
    if (SqlLoaderError.isSqlLoaderError(error)) {
      console.error(error.message);
      return error.code === 'ERR_SOURCE_NOT_FOUND' || error.code === 'ERR_INVALID_SOURCE' ? 2 : 1;
    }
    console.error(error instanceof Error ? error.message : String(error));
    return 2;
  }

  const rootDir = path.resolve(dir);
  try {
    fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
    if (format === 'ts') {
      fs.writeFileSync(out, emitTsModule(catalog.entries, rootDir, catalog.hash), 'utf8');
    } else {
      fs.writeFileSync(out, emitJsModule(catalog.entries, rootDir, catalog.hash), 'utf8');
      const dtsPath = out.replace(/\.mjs$/, '.d.mts').replace(/\.js$/, '.d.ts');
      fs.writeFileSync(dtsPath, emitDts(catalog.entries, catalog.hash), 'utf8');
    }
  } catch (error) {
    console.error(`sql-loader generate: ${error instanceof Error ? error.message : error}`);
    return 2;
  }

  console.log(`Generated ${out} (${catalog.entries.length} queries, ${catalog.hash})`);
  return 0;
}
