import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { emitKey, IDENTIFIER_RE } from '../emit';
import type { SqlEntry } from '../index';
import { loadSqlCatalogSync, SqlLoaderError } from '../index';

const pkg = createRequire(import.meta.url)('../../package.json') as { version: string };

const USAGE = 'Usage: sql-loader generate <dir> --out <file> [--format ts|js] [--dialect postgres]';

type Dialect = 'postgres' | null;

interface TreeNode extends Map<string, TreeNode | string> {}

function buildNestedMap(entries: readonly SqlEntry[]): TreeNode {
  const root: TreeNode = new Map();
  for (const entry of entries) {
    const segments = entry.id.split('/');
    let node = root;
    for (let i = 0; i < segments.length - 1; i++) {
      const key = segments[i] ?? '';
      let next = node.get(key);
      if (next === undefined || typeof next === 'string') {
        next = new Map();
        node.set(key, next);
      }
      node = next;
    }
    node.set(segments[segments.length - 1] ?? '', entry.text);
  }
  return root;
}

function emitValueNode(node: TreeNode, indent: string): string {
  const lines: string[] = ['{'];
  for (const [key, value] of node) {
    const rendered =
      typeof value === 'string' ? JSON.stringify(value) : emitValueNode(value, `${indent}  `);
    lines.push(`${indent}  ${emitKey(key)}: ${rendered},`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function emitTypeNode(node: TreeNode, indent: string): string {
  const lines: string[] = ['{'];
  for (const [key, value] of node) {
    const keyText = key === '__proto__' || !IDENTIFIER_RE.test(key) ? JSON.stringify(key) : key;
    const rendered = typeof value === 'string' ? 'string' : emitTypeNode(value, `${indent}  `);
    lines.push(`${indent}  readonly ${keyText}: ${rendered};`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function headerLines(hash: string, fileCount: number, dialect: Dialect): string[] {
  // Without --dialect the header (and the whole file) is byte-identical to
  // pre-dialect versions of the tool.
  const dialectField = dialect === null ? '' : ` dialect=${dialect}`;
  return [
    `// @generated by sql-loader v${pkg.version} — do not edit`,
    `// sql-loader:generated v=1 hash=${hash} files=${fileCount}${dialectField}`,
  ];
}

function relativePosixPath(rootDir: string, filePath: string): string {
  return path.relative(rootDir, filePath).replaceAll('\\', '/');
}

function emitEntries(entries: readonly SqlEntry[], rootDir: string): string {
  const lines: string[] = ['['];
  for (const entry of entries) {
    const rel = relativePosixPath(rootDir, entry.filePath);
    lines.push(
      `  { id: ${JSON.stringify(entry.id)}, text: ${JSON.stringify(entry.text)}, ` +
        `hash: ${JSON.stringify(entry.hash)}, path: ${JSON.stringify(rel)} },`,
    );
  }
  lines.push(']');
  return lines.join('\n');
}

function queryIdUnion(entries: readonly SqlEntry[]): string {
  if (entries.length === 0) return 'never';
  return entries.map((entry) => JSON.stringify(entry.id)).join(' | ');
}

// Statement artifacts (dialect mode only). `text` is the COMPILED positional
// text; `hash` stays the hash of the original text so it always matches
// `entries` and the directory hash.
function statementFields(entry: SqlEntry): string[] {
  const fields = [
    `id: ${JSON.stringify(entry.id)}`,
    `text: ${JSON.stringify(entry.compiledText ?? entry.text)}`,
    `parameters: [${(entry.parameters ?? []).map((p) => JSON.stringify(p)).join(', ')}]`,
  ];
  if (entry.positionalCount !== undefined) {
    fields.push(`positionalCount: ${entry.positionalCount}`);
  }
  if (entry.cardinality !== undefined) {
    fields.push(`cardinality: ${JSON.stringify(entry.cardinality)}`);
  }
  fields.push(`hash: ${JSON.stringify(entry.hash)}`);
  return fields;
}

function emitStatementsValue(entries: readonly SqlEntry[]): string[] {
  return [
    'export const statements = {',
    ...entries.map(
      (entry) => `  ${JSON.stringify(entry.id)}: { ${statementFields(entry).join(', ')} },`,
    ),
    '}',
  ];
}

function emitStatementsTs(entries: readonly SqlEntry[]): string[] {
  const value = emitStatementsValue(entries);
  const last = value.length - 1;
  return [
    '',
    "export type SqlCardinality = 'zero-or-one' | 'exactly-one' | 'many' | 'none';",
    '',
    ...value.slice(0, last),
    '} as const;',
    '',
    'export type SqlStatements = typeof statements;',
    '',
    'export type SqlParamsOf<Id extends SqlQueryId> = {',
    "  [K in SqlStatements[Id]['parameters'][number]]: unknown;",
    '};',
  ];
}

function emitStatementsJs(entries: readonly SqlEntry[]): string[] {
  const value = emitStatementsValue(entries);
  const last = value.length - 1;
  return ['', ...value.slice(0, last), '};'];
}

function emitStatementsDts(entries: readonly SqlEntry[]): string[] {
  const lines = [
    '',
    "export type SqlCardinality = 'zero-or-one' | 'exactly-one' | 'many' | 'none';",
    '',
    'export declare const statements: {',
  ];
  for (const entry of entries) {
    const fields = [
      `readonly id: ${JSON.stringify(entry.id)}`,
      'readonly text: string',
      `readonly parameters: readonly [${(entry.parameters ?? [])
        .map((p) => JSON.stringify(p))
        .join(', ')}]`,
    ];
    if (entry.positionalCount !== undefined) {
      fields.push(`readonly positionalCount: ${entry.positionalCount}`);
    }
    if (entry.cardinality !== undefined) {
      fields.push(`readonly cardinality: ${JSON.stringify(entry.cardinality)}`);
    }
    fields.push('readonly hash: string');
    lines.push(`  readonly ${JSON.stringify(entry.id)}: { ${fields.join('; ')} };`);
  }
  lines.push(
    '};',
    '',
    'export type SqlStatements = typeof statements;',
    '',
    'export type SqlParamsOf<Id extends SqlQueryId> = {',
    "  [K in SqlStatements[Id]['parameters'][number]]: unknown;",
    '};',
  );
  return lines;
}

function emitTsModule(
  entries: readonly SqlEntry[],
  rootDir: string,
  hash: string,
  dialect: Dialect,
): string {
  const tree = buildNestedMap(entries);
  return [
    ...headerLines(hash, entries.length, dialect),
    '',
    `export const queries = ${emitValueNode(tree, '')} as const;`,
    '',
    `export type SqlQueryId = ${queryIdUnion(entries)};`,
    '',
    'export interface SqlGeneratedEntry {',
    '  readonly id: SqlQueryId;',
    '  readonly text: string;',
    '  readonly hash: string;',
    '  readonly path: string;',
    '}',
    '',
    `export const entries: readonly SqlGeneratedEntry[] = ${emitEntries(entries, rootDir)};`,
    '',
    `export const sqlHash = ${JSON.stringify(hash)};`,
    '',
    'const byId = new Map<string, string>(entries.map((entry) => [entry.id, entry.text] as const));',
    '',
    'export function getSql(id: SqlQueryId): string {',
    '  const text = byId.get(id);',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emitted source code, not a mistaken template
    '  if (text === undefined) throw new Error(`Unknown SQL query ID: ${String(id)}`);',
    '  return text;',
    '}',
    ...(dialect === null ? [] : emitStatementsTs(entries)),
    '',
  ].join('\n');
}

function emitJsModule(
  entries: readonly SqlEntry[],
  rootDir: string,
  hash: string,
  dialect: Dialect,
): string {
  const tree = buildNestedMap(entries);
  return [
    ...headerLines(hash, entries.length, dialect),
    '',
    `export const queries = ${emitValueNode(tree, '')};`,
    '',
    `export const entries = ${emitEntries(entries, rootDir)};`,
    '',
    `export const sqlHash = ${JSON.stringify(hash)};`,
    '',
    'const byId = new Map(entries.map((entry) => [entry.id, entry.text]));',
    '',
    'export function getSql(id) {',
    '  const text = byId.get(id);',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: emitted source code, not a mistaken template
    '  if (text === undefined) throw new Error(`Unknown SQL query ID: ${String(id)}`);',
    '  return text;',
    '}',
    ...(dialect === null ? [] : emitStatementsJs(entries)),
    '',
  ].join('\n');
}

function emitDts(entries: readonly SqlEntry[], hash: string, dialect: Dialect): string {
  const tree = buildNestedMap(entries);
  return [
    ...headerLines(hash, entries.length, dialect),
    '',
    `export type SqlQueryId = ${queryIdUnion(entries)};`,
    '',
    'export interface SqlGeneratedEntry {',
    '  readonly id: SqlQueryId;',
    '  readonly text: string;',
    '  readonly hash: string;',
    '  readonly path: string;',
    '}',
    '',
    `export declare const queries: ${emitTypeNode(tree, '')};`,
    '',
    'export declare const entries: readonly SqlGeneratedEntry[];',
    '',
    'export declare const sqlHash: string;',
    '',
    'export declare function getSql(id: SqlQueryId): string;',
    ...(dialect === null ? [] : emitStatementsDts(entries)),
    '',
  ].join('\n');
}

export function runGenerate(argv: string[]): number {
  let dir: string;
  let out: string;
  let format: string;
  let dialect: Dialect = null;
  try {
    const parsed = parseArgs({
      args: argv,
      options: {
        out: { type: 'string', short: 'o' },
        format: { type: 'string', default: 'ts' },
        dialect: { type: 'string' },
      },
      allowPositionals: true,
      strict: true,
    });
    const positional = parsed.positionals[0];
    if (positional === undefined || parsed.positionals.length !== 1) {
      throw new Error('expected exactly one <dir> argument');
    }
    if (parsed.values.out === undefined) throw new Error('--out <file> is required');
    if (parsed.values.dialect !== undefined && parsed.values.dialect !== 'postgres') {
      throw new Error('--dialect must be "postgres"');
    }
    dir = positional;
    out = parsed.values.out;
    dialect = (parsed.values.dialect as 'postgres' | undefined) ?? null;
    format = parsed.values.format ?? 'ts';
    if (format !== 'ts' && format !== 'js') throw new Error('--format must be "ts" or "js"');
    if (format === 'ts' && !/\.(ts|mts)$/.test(out)) {
      throw new Error('--format ts requires an --out file ending in .ts or .mts');
    }
    if (format === 'js' && !/\.(js|mjs)$/.test(out)) {
      throw new Error('--format js requires an --out file ending in .js or .mjs');
    }
  } catch (error) {
    console.error(`sql-loader generate: ${error instanceof Error ? error.message : error}`);
    console.error(USAGE);
    return 2;
  }

  let catalog: ReturnType<typeof loadSqlCatalogSync>;
  try {
    catalog = loadSqlCatalogSync(dir, dialect === null ? undefined : { dialect });
  } catch (error) {
    if (SqlLoaderError.isSqlLoaderError(error)) {
      console.error(error.message);
      return error.code === 'ERR_SOURCE_NOT_FOUND' || error.code === 'ERR_INVALID_SOURCE' ? 2 : 1;
    }
    console.error(error instanceof Error ? error.message : String(error));
    return 2;
  }

  const rootDir = path.resolve(dir);
  try {
    fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
    if (format === 'ts') {
      fs.writeFileSync(out, emitTsModule(catalog.entries, rootDir, catalog.hash, dialect), 'utf8');
    } else {
      fs.writeFileSync(out, emitJsModule(catalog.entries, rootDir, catalog.hash, dialect), 'utf8');
      const dtsPath = out.replace(/\.mjs$/, '.d.mts').replace(/\.js$/, '.d.ts');
      fs.writeFileSync(dtsPath, emitDts(catalog.entries, catalog.hash, dialect), 'utf8');
    }
  } catch (error) {
    console.error(`sql-loader generate: ${error instanceof Error ? error.message : error}`);
    return 2;
  }

  console.log(`Generated ${out} (${catalog.entries.length} queries, ${catalog.hash})`);
  return 0;
}
