import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { after, before, test } from 'node:test';
import { fileURLToPath, pathToFileURL } from 'node:url';

const CLI = fileURLToPath(new URL('../../dist/cli/index.js', import.meta.url));
const FIXTURES = fileURLToPath(new URL('../fixtures/', import.meta.url));
const TSC = fileURLToPath(new URL('../../node_modules/typescript/lib/tsc.js', import.meta.url));

const fixture = (name) => path.join(FIXTURES, name);

const run = (args, options = {}) =>
  spawnSync(process.execPath, [CLI, ...args], { encoding: 'utf8', ...options });

const typecheck = (files) =>
  spawnSync(
    process.execPath,
    [
      TSC,
      '--noEmit',
      '--strict',
      '--skipLibCheck',
      '--target',
      'es2022',
      '--module',
      'esnext',
      '--moduleResolution',
      'bundler',
      ...files,
    ],
    { encoding: 'utf8' },
  );

let tmpDir;
before(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sql-loader-cli-'));
});
after(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

test('no command prints usage and exits 2', () => {
  const result = run([]);
  assert.equal(result.status, 2);
  assert.match(result.stderr, /Usage:/);
});

test('--help exits 0, unknown command exits 2', () => {
  assert.equal(run(['--help']).status, 0);
  const unknown = run(['frobnicate']);
  assert.equal(unknown.status, 2);
  assert.match(unknown.stderr, /unknown command/);
});

test('--version prints a version', () => {
  const result = run(['--version']);
  assert.equal(result.status, 0);
  assert.match(result.stdout.trim(), /^\d+\.\d+\.\d+/);
});

test('generate emits a deterministic ts module with a parseable header', () => {
  const out = path.join(tmpDir, 'basic.ts');
  const first = run(['generate', fixture('basic'), '--out', out]);
  assert.equal(first.status, 0, first.stderr);
  const firstBytes = fs.readFileSync(out, 'utf8');
  assert.match(firstBytes, /^\/\/ @generated by sql-loader/);
  assert.match(firstBytes, /^\/\/ sql-loader:generated v=1 hash=sha256-[0-9a-f]{64} files=5$/m);

  const second = run(['generate', fixture('basic'), '--out', out]);
  assert.equal(second.status, 0);
  assert.equal(fs.readFileSync(out, 'utf8'), firstBytes, 'two runs must be byte-identical');
});

test('generated ts modules pass tsc --strict (incl. quoted keys)', () => {
  const basicOut = path.join(tmpDir, 'typecheck-basic.ts');
  const namedOut = path.join(tmpDir, 'typecheck-named.ts');
  assert.equal(run(['generate', fixture('basic'), '--out', basicOut]).status, 0);
  assert.equal(run(['generate', fixture('named'), '--out', namedOut]).status, 0);
  const result = typecheck([basicOut, namedOut]);
  assert.equal(result.status, 0, `tsc failed:\n${result.stdout}${result.stderr}`);
});

test('generate --format js emits .js + .d.ts and the module works', async () => {
  const out = path.join(tmpDir, 'basic.js');
  const result = run(['generate', fixture('basic'), '--format', 'js', '--out', out]);
  assert.equal(result.status, 0, result.stderr);
  assert.ok(fs.existsSync(out));
  assert.ok(fs.existsSync(path.join(tmpDir, 'basic.d.ts')));

  const mod = await import(pathToFileURL(out));
  assert.equal(mod.queries.get.user.trim(), 'SELECT * FROM USER;');
  assert.equal(mod.getSql('get/user').trim(), 'SELECT * FROM USER;');
  assert.throws(() => mod.getSql('nope/nope'), /Unknown SQL query ID/);
  assert.equal(mod.entries.length, 5);
  assert.equal(mod.entries[0].path, 'get/get_sub/user.sql');
  assert.match(mod.sqlHash, /^sha256-/);
});

test('generate arg validation exits 2', () => {
  assert.equal(run(['generate', fixture('basic')]).status, 2);
  assert.equal(
    run(['generate', fixture('basic'), '--format', 'js', '--out', path.join(tmpDir, 'x.ts')])
      .status,
    2,
  );
  assert.equal(run(['generate', fixture('does-not-exist'), '--out', 'x.ts']).status, 2);
});

test('generate on invalid SQL content exits 1', () => {
  const result = run(['generate', fixture('collisions'), '--out', path.join(tmpDir, 'bad.ts')]);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /ERR_NAME_COLLISION|collides/);
});

test('check: clean directory exits 0 with JSON diagnostics', () => {
  const result = run(['check', fixture('basic'), '--json']);
  assert.equal(result.status, 0, result.stderr);
  const report = JSON.parse(result.stdout);
  assert.equal(report.ok, true);
  assert.equal(report.queries, 5);
  assert.match(report.hash, /^sha256-/);
  assert.deepEqual(report.diagnostics, []);
});

test('check: BOM is a warning, not a failure', () => {
  const result = run(['check', fixture('bom'), '--json']);
  assert.equal(result.status, 0);
  const report = JSON.parse(result.stdout);
  assert.equal(report.ok, true);
  assert.equal(report.diagnostics.length, 1);
  assert.equal(report.diagnostics[0].code, 'WARN_BOM');
  assert.equal(report.diagnostics[0].severity, 'warning');
});

test('check: collisions exit 1 with error diagnostics', () => {
  const result = run(['check', fixture('collisions'), '--json']);
  assert.equal(result.status, 1);
  const report = JSON.parse(result.stdout);
  assert.equal(report.ok, false);
  assert.ok(report.diagnostics.some((d) => d.code === 'ERR_NAME_COLLISION'));
});

test('check: missing directory exits 2', () => {
  assert.equal(run(['check', fixture('does-not-exist')]).status, 2);
});

test('check --generated: fresh, stale, and unparseable states', () => {
  const out = path.join(tmpDir, 'stale-check.ts');
  assert.equal(run(['generate', fixture('basic'), '--out', out]).status, 0);

  const fresh = run(['check', fixture('basic'), '--generated', out, '--json']);
  assert.equal(fresh.status, 0, fresh.stderr);
  assert.equal(JSON.parse(fresh.stdout).generated.status, 'fresh');

  const stale = run(['check', fixture('named'), '--generated', out, '--json']);
  assert.equal(stale.status, 1);
  assert.equal(JSON.parse(stale.stdout).generated.status, 'stale');

  const headerless = path.join(tmpDir, 'headerless.ts');
  fs.writeFileSync(headerless, 'export const queries = {};\n');
  const unparseable = run(['check', fixture('basic'), '--generated', headerless, '--json']);
  assert.equal(unparseable.status, 1);
  assert.equal(JSON.parse(unparseable.stdout).generated.status, 'unparseable');

  const missing = run(['check', fixture('basic'), '--generated', path.join(tmpDir, 'nope.ts')]);
  assert.equal(missing.status, 2);
});

test('relative <dir> resolves against the CLI cwd', () => {
  const result = run(['check', 'basic', '--json'], { cwd: FIXTURES });
  assert.equal(result.status, 0, result.stderr);
  assert.equal(JSON.parse(result.stdout).queries, 5);
});
